### ISSUE TITLE
The option "undo" don't working

### ISSUE THREAD

**Issue by wescley** [blavejr/OrganiseDesktop#70] opened 2019-07-04 20:25 UTC
Hi,

Good Nigth!

I tried to execute the program.
It cleaned my desktop, but when i tryied to execute the option "undo" nothing happening.

Holds

**Comment by blavejr** [comment] 2019-07-07 15:12
Hey @wescley I havent looked at this code for a while but if you would like to try and solve this issue that would be highly appreciated.

**Comment by safderareepattamannil** [comment] 2019-11-18 13:12
@blavejr I'm not sure I even see the undo script in OrganizeDesktop directory.

**Comment by KokoseiJ** [comment] 2020-01-22 12:27
@blavejr This might be necropost, but I've found the issue. The problem is this line in the function undo:
`if environ.get('TEST_DIR') != '':`
I guess this value is None or something like that, which is not same as empty string, I guess?
You can fix this by changing that line to:
`if environ.get('TEST_DIR'):`.
I've tested, now it works well.

**Comment by KokoseiJ** [comment] 2020-04-25 12:14
Fixed in PR #79. I'll close this issue.

**Closed by KokoseiJ** 2020-04-25 12:14 UTC
